apiVersion: v1
kind: ReplicationController
metadata:
  name: schema-registry
  namespace: kafka
spec:
  replicas: 1
  selector:
    app: schema-registry
  template:
    metadata:
      name: schema-registry
      labels:
        app: schema-registry
    spec:
      containers:
      - name: schema-registry
        image: docker.io/paulbrown/schema-registry:latest
        ports:
        - containerPort: 8081
