apiVersion: v1
kind: Service
metadata:
  name: http-proxy
  namespace: kafka
  labels:
    service: http-proxy
spec:
  ports:
    - name: client
      port: 8082
  clusterIP: None
  selector:
    app: http-proxy
