apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  namespace: kafka
  labels:
    service: kafka-manager
spec:
  ports:
    - name: client
      port: 9000
  clusterIP: None
  selector:
    app: kafka-manager
