apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: kafka
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-manager
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        #what version of kafka manager do we have?
        image: docker.io/sheepkiller/kafka-manager
        env:
        - name: ZK_HOSTS
          value: zookeeper:2181
        - name: APPLICATION_SECRET
          value: letmein
