apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: kafka
  labels:
    service: schema-registry
spec:
  ports:
    - name: client
      port: 8081
  clusterIP: None
  selector:
    app: schema-registry
