apiVersion: v1
kind: Service
metadata:
  name: schema-registry-ui
  namespace: kafka
  labels:
    service: schema-registry-ui
spec:
  ports:
    - port: 8000
  clusterIP: None
  selector:
    app: schema-registry-ui
