apiVersion: v1
kind: ReplicationController
metadata:
  name: schema-registry
  namespace: kafka
spec:
  replicas: 1
  selector:
    app: schema-registry
  template:
    metadata:
      name: schema-registry
      labels:
        app: schema-registry
    spec:
      containers:
      - name: schema-registry
        #image: landoop/confluentinc/cp-schema-registry:3.2.0
        image: docker.io/confluentinc/cp-schema-registry:3.2.0
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zookeeper:2181
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schema-registry
        ports:
        - containerPort: 8081
